name: Custom Avatars Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Blueprint Export
        uses: blueprint-community/action-export@v1.0.0

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: customavatars
          name: Custom Avatars
          tag_name: ${{ github.run_number }}-${{ github.run_id }}
          generate_release_notes: true
