name: Export Blueprint

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Blueprint Export
        uses: blueprint-community/action-export@v1.0.0
      
      - name: Rename to .blueprint
        run: mv blueprint.yaml blueprint.blueprint
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: blueprint.blueprint
          name: blueprint.blueprint
          tag_name: latest
          generate_release_notes: true